services:
  azure:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    env_file:
      - .env
    ports:
      - "22166:22166"
    networks:
      - bastion-network
    container_name: "azure-bastion"
networks:
  bastion-network:
    external: false
    name: bastion-network
